import type { Metadata } from "next";
import "./globals.css";

import { vt323, courier } from "@/fonts";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Pokon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={[vt323.variable, courier.variable, "h-full"].join(" ")}
    >
      <body className="font-body h-full grid grid-rows-global-layout">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
